workflows:
  ios-build:
    name: iOS IPA Build (Manual Export)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build Flutter iOS App (Release)
        script: |
          flutter build ios --release --no-codesign
      - name: Use Automatic Signing
        script: |
          xcode-project use-profiles
      - name: Export IPA
        script: |
          xcode-project build-ipa \
            --project ios/Runner.xcodeproj \
            --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.dSYM.zip
