workflows:
  ios-build:
    name: iOS IPA Build (with automatic signing)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Set Code Signing
        script: |
          xcode-project use-profiles
      - name: Archive and Export
        script: |
          xcode-project build-ipa \
            --project ios/Runner.xcodeproj \
            --scheme Runner
    artifacts:
      - build/ios/ipa/*.ipa
