// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///import 'package:firebase_core/firebase_core.dart';
///import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    /// case TargetPlatform.web:
    ///   return web;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI command `flutterfire configure`.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV3PZd7rLbppacAnq6Q12R2kouALhY3u4',
    appId: '1:758079153152:android:508d83c7c6e672ae6a64e5',
    messagingSenderId: '758079153152',
    projectId: 'hanappproject',
    storageBucket: 'hanappproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMoXz9bLlw8i3o0KACTVaPsKmFM2rCOFI',
    appId: '1:723085540061:ios:d120a7d6aeb83f46e43934',
    messagingSenderId: '723085540061',
    projectId: 'hanapp-15bf7-38147',
    storageBucket: 'hanapp-15bf7-38147.firebasestorage.app',
    iosClientId: '723085540061-g3ev7n5h2ka4vm230ki66dt5hnoisjlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.hanapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMoXz9bLlw8i3o0KACTVaPsKmFM2rCOFI',
    appId: '1:723085540061:ios:d120a7d6aeb83f46e43934',
    messagingSenderId: '723085540061',
    projectId: 'hanapp-15bf7-38147',
    storageBucket: 'hanapp-15bf7-38147.firebasestorage.app',
    iosClientId: '723085540061-g3ev7n5h2ka4vm230ki66dt5hnoisjlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.hanapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMoXz9bLlw8i3o0KACTVaPsKmFM2rCOFI',
    appId: '1:723085540061:web:d120a7d6aeb83f46e43934',
    messagingSenderId: '723085540061',
    projectId: 'hanapp-15bf7-38147',
    authDomain: 'hanapp-15bf7-38147.firebaseapp.com',
    storageBucket: 'hanapp-15bf7-38147.firebasestorage.app',
    measurementId: 'G-SCTZ90QWM7',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMoXz9bLlw8i3o0KACTVaPsKmFM2rCOFI',
    appId: '1:723085540061:web:d120a7d6aeb83f46e43934',
    messagingSenderId: '723085540061',
    projectId: 'hanapp-15bf7-38147',
    authDomain: 'hanapp-15bf7-38147.firebaseapp.com',
    storageBucket: 'hanapp-15bf7-38147.firebasestorage.app',
    measurementId: 'G-ZX864V4R9Q',
  );

}